// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWxloletirw5P9H5Zvv7j6Len0K_3_j0',
    appId: '1:671402876268:web:ab6c5d55b441a64c1a2749',
    messagingSenderId: '671402876268',
    projectId: 'mbp-tracker-dev',
    authDomain: 'mbp-tracker-dev.firebaseapp.com',
    storageBucket: 'mbp-tracker-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3nAAQZB_LTWxKuqGLyiwkEGAnbmbxdI',
    appId: '1:671402876268:android:0bf9493149d7dea41a2749',
    messagingSenderId: '671402876268',
    projectId: 'mbp-tracker-dev',
    storageBucket: 'mbp-tracker-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ICXg9KToteYiqbj40tJGsHc2J4alSuY',
    appId: '1:671402876268:ios:ad8716d914ed68b51a2749',
    messagingSenderId: '671402876268',
    projectId: 'mbp-tracker-dev',
    storageBucket: 'mbp-tracker-dev.firebasestorage.app',
    iosClientId: '671402876268-ucrqgj3jcnvjd2j8jrvebii6gb0jcu89.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiBrokerPortfolio',
  );
}
